fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
frontend_registration:
    pattern:  /profil/regisztracio
    defaults: { _controller: FrontendUserBundle:Default:registration}
    
frontend_login:
    pattern:  /profil/bejelentkezes
    defaults: { _controller: FrontendUserBundle:Default:login}   

frontend_login_check:
    pattern:  /profil/bejelentkezes/ellenorzed
    defaults: { _controller: FrontendUserBundle:Default:checkLogin}
    
frontend_registration_email_check:
    pattern:  /profil/regisztracio/email/ellenorzes
    defaults: { _controller: FrontendUserBundle:Default:emailCheck}           

    
frontend_password_confirmation:
    pattern:  /profil/uj-jelszo/{confirmationToken}
    defaults: { _controller: FrontendUserBundle:Default:passwordConfirmation} 
    
frontend_password_reset:
    pattern:  /profil/uj-jelszo
    defaults: { _controller: FrontendUserBundle:Default:passwordReset}  
        
frontend_password_reset_with_token:
    pattern:  /profil/uj-jelszo/valtoztat/
    defaults: { _controller: FrontendUserBundle:Default:passwordResetWithConfirmaionToken}