parameters:
#    frontend_layout.example.class: Frontend\LayoutBundle\Example

services:
#    frontend_layout.example:
#        class: %frontend_layout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     frontend.twig.price_format_extension:
        class: Frontend\LayoutBundle\Twig\PriceFormatExtension
        tags:
            - { name: twig.extension }   
