frontend_profile:
    resource: "@FrontendProfileBundle/Resources/config/routing.yml"
    prefix:   /

frontend_user:
    resource: "@FrontendUserBundle/Resources/config/routing.yml"
    prefix:   /

frontend_product:
    resource: "@FrontendProductBundle/Resources/config/routing.yml"
    prefix:   /

frontend_layout:
    resource: "@FrontendLayoutBundle/Resources/config/routing.yml"
    prefix:   /

