frontend_cart:
    resource: "@FrontendCartBundle/Resources/config/routing.yml"
    prefix:   /

backend_layout:
    resource: "@BackendLayoutBundle/Resources/config/routing.yml"
    prefix:   /

backend_admin:
    resource: "@BackendAdminBundle/Resources/config/routing.yml"
    prefix:   /

frontend_profile:
    resource: "@FrontendProfileBundle/Resources/config/routing.yml"
    prefix:   /

frontend_user:
    resource: "@FrontendUserBundle/Resources/config/routing.yml"
    prefix:   /

frontend_product:
    resource: "@FrontendProductBundle/Resources/config/routing.yml"
    prefix:   /

frontend_layout:
    resource: "@FrontendLayoutBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile