frontend_cart_orders:
    pattern:  /kosar/rendeles
    defaults: { _controller: FrontendOrderBundle:Order:orders}    
    
frontend_cart_orders_success:
    pattern:  /kosar/rendeles/leadva
    defaults: { _controller: FrontendOrderBundle:Order:success}        