parameters:
#    frontend_order.example.class: Frontend\OrderBundle\Example

services:
#    frontend_order.example:
#        class: %frontend_order.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
