backend_admin:
    pattern:  /admin
    defaults: { _controller: BackendAdminBundle:Index:login }
#
# termékek szerkesztése   
#
backend_admin_product:
    pattern:  /admin/termekek
    defaults: { _controller: BackendAdminBundle:Product:list }
    
backend_admin_product_new:
    pattern:  /admin/termekek/uj
    defaults: { _controller: BackendAdminBundle:Product:new }
    
backend_admin_product_remove:
    pattern:  /admin/termekek/torles
    defaults: { _controller: BackendAdminBundle:Product:remove }
    
backend_admin_product_upload_image:
    pattern:  /admin/termekek/uj-kep
    defaults: { _controller: BackendAdminBundle:Image:upload }
    
backend_admin_product_property_list:
    pattern:  /admin/termekek/tulajdonsagok
    defaults: { _controller: BackendAdminBundle:Product:propertyList }    
    
backend_admin_product_property_edit:
    pattern:  /admin/termekek/tulajdonsagok/szerkesztes/{productId}/{propertyId}/
    defaults: { _controller: BackendAdminBundle:Product:propertyNew }    

backend_admin_product_property_remove:
    pattern:  /admin/termekek/tulajdonsagok/torles
    defaults: { _controller: BackendAdminBundle:Product:propertyRemove }
    
backend_admin_product_select_category_ajax:
    pattern:  /admin/termekek/kategoria/select
    defaults: { _controller: BackendAdminBundle:Product:selectCategoryAjax }           
#
# kategóriák szerkesztése    
#
backend_admin_category:
    pattern:  /admin/kategoria
    defaults: { _controller: BackendAdminBundle:Category:index }
    
backend_admin_category_new:
    pattern:  /admin/kategoria/uj
    defaults: { _controller: BackendAdminBundle:Category:new }
    
backend_admin_category_remove:
    pattern:  /admin/kategoria/torles
    defaults: { _controller: BackendAdminBundle:Category:remove }
    
backend_admin_main_category:
    pattern:  /admin/fokategoria
    defaults: { _controller: BackendAdminBundle:Category:mainCategory }    
        
backend_admin_main_category_new:
    pattern:  /admin/fokategoria/uj
    defaults: { _controller: BackendAdminBundle:Category:mainCategoryNew }
    
backend_admin_main_category_remove:
    pattern:  /admin/fokategoria/torles
    defaults: { _controller: BackendAdminBundle:Category:removeMainCategory }
# 
# felhasználók szerkesztése
#
backend_admin_user:
    pattern:  /admin/felhasznalok
    defaults: { _controller: BackendAdminBundle:User:list }    
    
backend_admin_user_new:
    pattern:  /admin/felhasznalok/uj
    defaults: { _controller: BackendAdminBundle:User:new }
    
backend_admin_user_remove:
    pattern:  /admin/felhasznalok/torles
    defaults: { _controller: BackendAdminBundle:User:remove }    

backend_admin_profile_edit:
    pattern:  /admin/felhasznalok/profil/szerkesztes
    defaults: { _controller: BackendAdminBundle:User:profileEdit }
    
#
# képek szerkesztése
#
backend_admin_product_image_remove:
    pattern:  /admin/termekek/kepek/torles
    defaults: { _controller: BackendAdminBundle:Image:remove }   
    
#
# rendelések
#
backend_admin_order_list:
    pattern:  /admin/rendelesek
    defaults: { _controller: BackendAdminBundle:Order:list }
    
backend_admin_order_list_more:
    pattern:  /admin/rendelesek/{orderId}/bovebben
    defaults: { _controller: BackendAdminBundle:Order:listMore }    
    
backend_admin_order_fulfill:
    pattern:  /admin/rendelesek/{orderId}/teljesites
    defaults: { _controller: BackendAdminBundle:Order:fulfillOrder }   
    
#
# tulajdonságok szerkesztése    
#
backend_admin_property:
    pattern:  /admin/tulajdonsagok
    defaults: { _controller: BackendAdminBundle:Property:list }
    
backend_admin_property_new:
    pattern:  /admin/tulajdonsagok/uj
    defaults: { _controller: BackendAdminBundle:Property:new }
    
backend_admin_property_remove:
    pattern:  /admin/tulajdonsagok/torles
    defaults: { _controller: BackendAdminBundle:Property:remove }