frontend_header_search_autocomplete:
    pattern: /kereses/autocomplete/
    defaults: { _controller: FrontendSearchBundle:Default:mainSearchAutocomplete }
    
frontend_header_search:
    pattern: /kereses/
    defaults: { _controller: FrontendSearchBundle:Default:mainSearch }