frontend_product_homepage:
    pattern:  /
    defaults: { _controller: FrontendProductBundle:Default:index }

product_by_taxonomy:
    pattern:  /t/{taxon}/{taxonomy}
    defaults: { _controller: FrontendProductBundle:Default:productByTaxonomy }

product_by_taxon:
    pattern:  /t/{taxon}/
    defaults: { _controller: FrontendProductBundle:Default:productByTaxonomy }

product:
    pattern:  /p/{slug}
    defaults: { _controller: FrontendProductBundle:Default:product }

frontend_registration:
    pattern:  /regisztracio
    defaults: { _controller: FrontendProductBundle:Default:registration}
    
frontend_login:
    pattern:  /bejelentkezes
    defaults: { _controller: FrontendProductBundle:Default:login}
