frontend_product_homepage:
    pattern:  /
    defaults: { _controller: FrontendProductBundle:Default:index }

product_by_category:
    pattern:  /t/{main_category}/{category}
    defaults: { _controller: FrontendProductBundle:Default:productByCategory }

product_by_main_category:
    pattern:  /t/{main_category}/
    defaults: { _controller: FrontendProductBundle:Default:productByCategory }

product:
    pattern:  /p/{slug}
    defaults: { _controller: FrontendProductBundle:Default:product }
    
frontend_product_questions:
    pattern:  /kerdesek/uj
    defaults: { _controller: FrontendProductBundle:Default:tabQuestions }
