parameters:
#    frontend_product.example.class: Frontend\ProductBundle\Example

services:
#    frontend_product.example:
#        class: %frontend_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
