parameters:
    product_service.class: Frontend\ProductBundle\Services\ProductServices

services:
    product_service:
        class: "%product_service.class%"
        arguments: [ @doctrine.orm.entity_manager, '@service_container', '@doctrine' ]     
    #termék tulajdonságainak rendezéses    
    frontend.twig.property_sort_extension:
        class: Frontend\ProductBundle\Twig\PropertySortExtension
        tags:
            - { name: twig.extension }    
    frontend.twig.property_converter_extension:
        class: Frontend\ProductBundle\Twig\PropertyConverterExtension
        tags:
            - { name: twig.extension } 